### ISSUE TITLE
Re-add creative mode instant shell construction

### ISSUE THREAD

**Issue by Noaaan** [Kira-NT/sync-fabric#1]
Back in the original mod there was a check when you used a shell constructor which would instantly finish a shell if you were in creative mode. This lets you create a large amount of clones without waiting for them to slowly construct.

**Comment by Kira-NT** [comment]
Are you sure? Don't remember this was a thing. Anyway, this is a good idea! Will be added as an opt-out feature

P.S. - at the moment you can use endermen to speed up the process \**wink-wink*\*

https://github.com/Kir-Antipov/sync-fabric/blob/ae5f63210a131490432fc267fc50e6f2d98f6d8e/src/main/java/me/kirantipov/mods/sync/block/entity/TreadmillStateManager.java#L139-L148
