### ISSUE TITLE
Requiem compat idea

### ISSUE THREAD

**Issue by alexmozaidze** [Kira-NT/sync-fabric#11]
Just an idea, I actually didn't try to launch Requiem with Sync. The idea is that demons can create dummy clones that they wouldn't be able to possess as they are a wandering spirit, and a clone is just a vessel for a mind, not soul (kind of like in hardcore, where if the original body dies - it's game over)

**Comment by Kira-NT** [comment]
Could you elaborate, please? 'Cause I don't quite understand what you mean by 'dummy clones'. Demons can't interact with things already, can they?

**Comment by alexmozaidze** [comment]
I mean, when a demon possesses a mob, things become interactable. By "dummy clones" I mean that if demon player that's controlling a mob interacts with the shell constructor - it works, but the demon player wouldn't be able to use that clone, and the clone itself would represent the possessed mob, that's forever stuck in shell constructor.

**Comment by Kira-NT** [comment]
Demons cannot use shell storages, because undead mobs, possessed by them, are exactly 2 blocks tall. Which is not much taller than a player, but it's enough to make entering a shell storage impossible.
So, in some way you request is already accidentally implemented xD

**Comment by alexmozaidze** [comment]
Wait, I just realized. What about the mobs that are shorter than the player? Like a baby zombie?

**Comment by Kira-NT** [comment]
Baby zombies can be possessed? 0_•
Child abuse detected!

Welp, ok, then I actually need to go and write some code
