### ISSUE TITLE
[Feature Request] Add Support for Origins Mod

### ISSUE THREAD

**Issue by marcoroegner** [Kira-NT/sync-fabric#15]
https://www.curseforge.com/minecraft/mc-mods/origins
https://www.curseforge.com/minecraft/mc-mods/origins-classes

Give shells the ability to choose an origin/class on first enter. So that different shells can have different origins/classes.

I think that would create some great gameplay possibility's!

**Comment by Kira-NT** [comment]
Won't make it in the next update, but I'm working on this

**Comment by marcoroegner** [comment]
Nice!
