### ISSUE TITLE
Shells are not being rendered when playing on server

### ISSUE THREAD

**Issue by nillawafers4u** [Kira-NT/sync-fabric#18]
### What happened?

for some reason trying to create a shell on my server that has both the tech reborn(1.18 beta versions) mod and sync (3.0) installed will not work. Meanwhile in a single player world they work just fine together without issue. 

Everything seems to work as it should right up until the constructor should start "printing" at which point no entities on treadmills will run (as if the constructor isn't trying to create a shell) likewise using power from a different mod has no effect on the constructor. It simply remains empty, but right clicking a second time will give you the "this constructor already has something" message.

no idea what causes these mods to conflict but there you go.

Let me know if you need anything else from me

### Version

sync-mc1.18-3.0.jar

### Minecraft Version

1.18.1

### Fabric API Version

0.44.0+1.18

### Installation Source

CurseForge

### Other Mods
- sync 3.0
- techreborn 5.1.0-beta.4
``

``

### Additional Information

like I stated above this problem only occurs when playing on a dedicated server ( LAN servers work completely fine)

**Comment by rsjonah** [comment]
Hey there, after extensive testing. I have found that its the 1.18 version of the tech reborn mod causing this issue.
for some reason if tech reborn is loaded on a server with sync no shells will be built.

**Comment by Kira-NT** [comment]
Oh, I can see that. Actually, your shell is in fact constructing and you can sync with it when it's done, it's just not rendering for some reason.

**Comment by Kira-NT** [comment]
Oh no, the problem is much worse - my block entities are not being synchronized with the client-side in general... Welp, the mod is playable, it's just visually broken

**Comment by Kira-NT** [comment]
>  [1.18.1] Fabric API 0.45.0+1.18 Latest
> - Fixes #1921: Synchronize BlockEntityType to the client since mods use the Vanilla mechanism for block entity updates since 1.18. (#1923) (shartte)

Please, update fabric api to `0.45.0+18`, and everything will work just fine
