### ISSUE TITLE
Add support for tech mods

### ISSUE THREAD

**Issue by Matiam0** [Kira-NT/sync-fabric#2]
List of tech mods to look into:

- [Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn)
- [Modern Industrialization](https://www.curseforge.com/minecraft/mc-mods/modern-industrialization)
- [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution)

I think that's all of them beside Buildcraft that has yet to release anything, so I might check back in and add it when it does.

**Comment by Kira-NT** [comment]
Thanks a lot! I think, few pseudo-mixins will do the trick :)

**Comment by Kira-NT** [comment]
It was even easier than I thought :)

### Tech Reborn

![image](https://user-images.githubusercontent.com/40232067/130328725-58f7049b-7b32-4314-b498-f20db9b2f9b5.png)

### Modern Industrialization

![image](https://user-images.githubusercontent.com/40232067/130329522-86ab2e32-532a-4a15-a4a0-a195619e3444.png)

### Industrial Revolution

![image](https://user-images.githubusercontent.com/40232067/130328538-be4157ae-f2b1-48ac-bfec-60e3e5a1a7c0.png)

**Comment by Kira-NT** [comment]
Closing the issue at the moment, since I don't think that release of the BuildCraft mod is somewhere around the corner. Feel free to open a new one when this will happen though

**Comment by Matiam0** [comment]
Looks like [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution) is no longer working
![2021-11-11_15 35 20](https://user-images.githubusercontent.com/63567491/141372593-d888008d-e008-4cf4-91b9-8d753b26354f.png) Doesn't even attach without the wrench anymore.

**Comment by Kira-NT** [comment]
`FastTransferLib` was deprecated, therefore latest versions of the tech mods use `TechReborn Energy`, and so [do I](https://github.com/Kir-Antipov/sync-fabric/commit/db220f210825cbc107d42459488b92c725401e80)

You can grab one of the most recent dev builds or wait for a new release to be published
