### ISSUE TITLE
[Bug] Shell Storages destroy my shells and doesn't let me repair them.

### ISSUE THREAD

**Issue by ZaneFlynt01** [Kira-NT/sync-fabric#23]
### What happened?

So, I was a huge fan of the original sync mod, so when I found this, I was like, "Hell yeah!" Though, in the latest version of it I downloaded (the version where the file is sync-mc1.18-3.1.jar), I encountered a bug where my shell storages weren't actually storing my shells properly, yet when stepping into another shell storage it still listed them as being there.

Whenever I try to select one of my shells, it says:
**The selected shell cannot be found.**

When I found there was the /sync command in the game, I thought that using it to fix them would repair the issue, yet it states that the coordinates used don't contain a shell storage. The issue is though is that I don't specify specific coordinates, thus causing the mod to have to physically locate the coordinates where the shell storage is to be able to give me the error message in the first place. 

What I get when entering the command, /sync repair @a (or whatever the command is my memory isn't that good),  is something along the lines of
**Failed to repair shell storage at [insert coordinates here]. The selected coordinates does not contain a Shell Storage.**

I wanted to report it because I didn't have this issue in an older version of the mod that I played, though I don't remember specifically what version. I thought it may be due to the other mods I'm using, but I don't know for sure.

### Version

3.1

### Minecraft Version

1.18.1

### Fabric API Version

0.46.1

### Installation Source

CurseForge

### Other Mods

```shell
All the other mods I'm using are:

-3D Skin Layers (1.3.1)
-Architectury API (3.4.9)
-Atlantis (2022.1.28-1.188-1.0.0)
-Cam's Backpacks (2.8)
-Clotrh API (3.1.61)
-Crawl (Fabric) (0.10.2)
-Elemental Creepers: Refabricated (1.4.1+1.18.1)
-Fabric API (0.46.1)
-Geckolib (3.0.30)
-Identity (1.16.0-1.18.1)
-Lamb Dynamic Lights (2.1.0)
-Mod Menu (3.0.1)
-No AI Spawn Eggs (Fabric) (10.0.4)
-Portal Gun (Fabric) (3.0.1)
-Prefab (3.0.2)
-Reborn Core (5.1.0 beta 7)
-Tech Reborn (5.1.0 beta 7)
-REI (7.2.416)
-Sandwichable (1.2-rc3A)
-'Slight' GUI Modifications (2.0.3)
-Sodium (0.4.0-alpha6+build.14)
-Starry Skies (1.5.1)
-Survival Plus (0.1.6b)
-Survival Plus Primer (0.1.0b)
-Survival Plus Lightsabers (0.1.6b)
-Valley (2.2.1)

If one of these mods is causing the issue, then lmk.
```

### Additional Information

Most of the settings are default, although I did set it so that:

-Redstone can be used as a power source.
-it doesn't require health to create a shell.

**Comment by Kira-NT** [comment]
Could you elaborate, please? It says «shell storage**s**», so does this happen to you regularly?

The `/sync ghostshells repair` command requires an existing empty shell storage to be present at the same position as the missing shell.
Please, locate the crosshair at the bottom part of the one, then type `/sync ghostshells repair Your_Nickname ` and press `Tab` 3 times (therefore the command will be completed with the coords of the block you're looking at) and execute the command. If the problem persists, I'd ask you to make a screenshot in the same position with debug screen (`F3`) and chat output being visible

**Comment by ZaneFlynt01** [comment]
I don't know how to elaborate any further. I go into my shell storage and
choose either another shell in storage or to the one in my shell
constructor, i wait only for a minute, and then when I choose the shell
while I'm in another shell storage, it says the shell cannot be found.
Nothing I do fixes it. Not even destroying it. When I destroy it, the shell
still comes up as a selectable shell to use.

Edit:

I'm saying Shell Storages because it happens to multiple at a time, so I'm using it as the plural to storage. And yes, this has happened regularly while I use the version I mentioned originally.

I've tried on multiple worlds several times and, if aything, I end up leaving the world with only like one or two of them working.

**Comment by Kira-NT** [comment]
It would be very nice of you if you could provide me with one of your worlds where the problem has happened, and maybe with your modpack, so I don't have to assemble it myself
