### ISSUE TITLE
[Feature Request] Lightning Charges Constructors

### ISSUE THREAD

**Issue by ttamttamS** [Kira-NT/sync-fabric#24]
### Problem

I want to use sync for my hardcore game, but the treadmills are cute and silly which breaks the tension a little too much, and the fabric ecosystem currently lacks a tech mod that I find engaging. So there's no *immersive* way to charge constructors.

### Feature

Why not Frankenstein it up a little? When struck by lightning the constructor charges an amount. Then placing a lightning rod on top (or beside I guess, *if you hate aesthetics...*) would be a valid mechanic for attracting lightning to charge it. Best part is unwaxed copper already de-oxidizes when struck, so the code *should* already be there to hook into (though idk how bad Minecraft's codebase is to work with so maybe not).

### Other Solutions

Maybe you could charge it with beacons, removing their status effects but charging it based on pyramid size?

**Comment by Kira-NT** [comment]
I like this suggestion. Sadly, I cannot implement this feature directly in this project, because it will change the way vanilla block (lightning rod) interacts with tech mods, but I will consider making a small separate mod for that after the war ends.

**Comment by ttamttamS** [comment]
Thanks for taking the time to look over this. Stay safe.

**Comment by Kira-NT** [comment]
Implemented via [Kir-Antipov/lightning-power](https://github.com/Kir-Antipov/lightning-power)
