### ISSUE TITLE
[Crash] The game crashes when Iris is present

### ISSUE THREAD

**Issue by Chill907Gaming** [Kira-NT/sync-fabric#27]
### Related Project(s)

Sodium and Iris 

### Problem

Currently launching the game with sodium and iris results in a crash. When you have time please look into this as I really really want to use your mod but I also require shaders and sodium.

### Feature

Maybe this is just a bug and they are normally compatible. But as of 1.19 they are not. Making these work for 1.19 would make many gamers happy.

### Justification

I support Ukraine !

**Comment by Kira-NT** [comment]
Thank you for the report! Note for the future, use the "Crash" template for such issues. Could you, please, attach a crash log?

**Comment by Kira-NT** [comment]
Works with Sodium
![image](https://user-images.githubusercontent.com/40232067/173227634-bc47dd58-ec10-4f13-ab02-74fbd07f95a6.png)
