### ISSUE TITLE
[Crash] Server crash when using shell constructor

### ISSUE THREAD

**Issue by antimockingjay** [Kira-NT/sync-fabric#49]
### What were you doing when the crash occured?

The crash occurs when right-clicking the shell constructor. It happens regardless of gamemode; I tried in both survival and creative to be sure it wasn't an issue with the damage dealing. Every time I try it, the server crashes. It does not cause the clientside instance of Minecraft to crash, but I haven't tested in singleplayer.

### Did the crash occur client-side or server-side?

Server

### Version

sync-mc1.19.1-4.3-jar

### Minecraft Version

1.19.2

### Fabric API Version

0.16.9

### Installation Source

CurseForge

### Logs

```shell
Latest log: https://mclo.gs/37EXRY9
Crash log: https://mclo.gs/ws6tyqa
```

### Other Mods

```shell
(copied directly from modlist.html)


    Mob Origins (by UltrusBot)
    Extra Origins (by MoriyaShiine)
    YUNG's Better Ocean Monuments (Fabric) (by YUNGNICKYOUNG)
    YetAnotherConfigLib (by isXander)
    Nature's Compass (by Chaosyr)
    Macaw's Doors (by sketch_macaw)
    Harvest with ease (by CrystalSpider)
    Xaero's Minimap (by xaero96)
    BetterNether (by Quiqueck)
    Sync (Fabric) (by Kir_Antipov)
    Grim's Transportables (by TheGrimsey)
    YUNG's Extras (Fabric) (by YUNGNICKYOUNG)
    Friends&Foes - Flowery Mooblooms (Fabric/Quilt) (by Faboslav)
    YUNG's Better Witch Huts (Fabric) (by YUNGNICKYOUNG)
    Pehkui (by Virtuoel)
    Iris Shaders (by coderbot)
    Macaw's Furniture (by sketch_macaw)
    Macaw's Trapdoors (by sketch_macaw)
    Haunted Harvest (by MehVahdJukaar)
    Croptopia's Chocolaterie [Fabric] (by slomax907)
    What Are They Up To (Watut) (by Corosus)
    Macaw's Paths and Pavings (by sketch_macaw)
    Origins: Classes (by Apace)
    YUNG's API (Fabric) (by YUNGNICKYOUNG)
    Friends&Foes - Beekeeper Hut (Fabric/Quilt) (by Faboslav)
    Macaw's Windows (by sketch_macaw)
    Extra Classes - Origins (by proman468)
    Macaw's Bridges (by sketch_macaw)
    YUNG's Bridges (Fabric) (by YUNGNICKYOUNG)
    Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)
    Balm (Fabric Edition) (by BlayTheNinth)
    Deeper and Darker (by KyaniteMods)
    Clumps (by Jaredlll08)
    Croptopia (by thethonk)
    cAn i MiNe thIS bLOCk? (by shedaniel)
    Fabric Seasons (by D4rkness_King)
    CoroUtil (by Corosus)
    Macaw's Paintings (by sketch_macaw)
    Macaw's Lights and Lamps (by sketch_macaw)
    Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)
    Origins (Fabric) (by Apace)
    MCA Reborn [Fabric/Forge] (by jahx_senpoopie)
    bad packets (by badasintended)
    Macaw's Roofs (by sketch_macaw)
    Moonlight Lib (by MehVahdJukaar)
    Just Enough Professions (JEP) (by Mrbysco)
    Architectury API (Fabric/Forge/NeoForge) (by shedaniel)
    Fabric Seasons: Croptopia Compat (by D4rkness_King)
    Fabric API (by modmuss50)
    Configured (Fabric) (by MrCrayfish)
    Friends & Foes (Fabric/Quilt) (Copper Golem,Glare,Crab,Moobloom,Iceologer,Rascal,Tuff Golem,Wildfire,Illusioner) (by Faboslav)
    Cobweb (by CrystalSpider)
    Just Enough Resources (JER) (by way2muchnoise)
    BCLib (by Quiqueck)
    AppleSkin (by squeek502)
    Cooking for Blockheads (Fabric Edition) (by BlayTheNinth)
    Mouse Tweaks (by YaLTeR)
    BetterEnd (by Quiqueck)
    Diggus Maximus (by Kyrptonaught)
    Forge Config API Port (by Fuzs)
    WTHIT (by badasintended)
    YUNG's Better Dungeons (Fabric) (by YUNGNICKYOUNG)
    Sodium (by JellySquid)
    FabricSkyboxes (by AMereBagatelle)
    Waystones (Fabric Edition) (by BlayTheNinth)
    Just Enough Items (JEI) (by mezz)
    Macaw's Fences and Walls (by sketch_macaw)
    Fabric Seasons: Extras (by D4rkness_King)
    Just Enough Painting Previews (JEPP) (by MehVahdJukaar)
    Origins++ (by QuantumXenon)
    Macaw's Holidays (by sketch_macaw)
    Simple Voice Chat (by henkelmax)
    Ears (+ Snouts/Muzzles, Tails, Horns, Wings, and More) (by unascribed)
    Just Enough Breeding (JEBr) (by Christofmeg)
    Macaw's Stairs (by sketch_macaw)
    Medieval Origins Revival [Forge/Neo/Fabric] (by MuonR)
```

### Additional Information

To be sure it wasn't a configuration issue, I reset the config options to default and tried, which still caused the crash upon right-clicking the shell constructor. Also worth noting is that none of the devices seem to register as being powered, according to WTHIT's popup; this includes constructors and storage.

**Comment by Kira-NT** [comment]
Yup, I know :D It's a duplicate of #46. Sadly, haven't time to fix it yet, because I plan on rewriting huge portions of this mod.

**Comment by antimockingjay** [comment]
Are there any workarounds to get it to work, be it with commands, creative mode, or anything else? We're really only using the mod for those of us on the server with DID so each alter can have their own origins, inventory, etc., so losing the survival aspect of things isn't a big deal if there's some sort of workaround we can use.

**Comment by Kira-NT** [comment]
Wow, this mod has become unexpectedly popular amongst the DID folks! I guess I really need to revive it ASAP if it helps people :)

So, here's the issue: the mod worked perfectly fine until Fabric changed how its `@Environment` annotation is processed. The last time I tested the mod, it was with Fabric Loader 0.14.9. If you're able to downgrade to that version, the mod should start working again. You could also try 0.15.0, as it's not too far off from 0.14.9 and also includes MixinExtras, which many modern mods rely on.

Unfortunately, if downgrading isn't an option, there's no workaround. This issue affects the very core component of this mod, making it impossible to resolve without an update.

P.S. - the mod still works in singleplayer, tho.

**Comment by antimockingjay** [comment]
I mean it's a shockingly perfect way to manage stuff without having to get separate accounts for every alter! It's definitely helpful for us, it makes it so the inventory swapping and changing origins/classes just happens automatically in one step rather than having to unload all of your gear manually and figure out a way people can swap origins without giving everyone access to all commands. As for as reviving it ASAP, we're definitely rooting for you, but definitely don't push yourself too hard, either.

Downgrading would, unfortunately, mean downgrading all the other mods on the server, which would be an annoyance for all the other players of the server, so for now we'll probably just do things the old fashioned way until the mod is updated. Until then we'll eagerly await an update!

P.S. - we will definitely be using it in all our singleplayer saves still.
