### ISSUE TITLE
Add Trinkets support

### ISSUE THREAD

**Issue by alexmozaidze** [Kira-NT/sync-fabric#6]
Currently items in Trinket slots don't stay with the shell but are instead transferred along with the mind.

**Comment by Kira-NT** [comment]
It's on the list :)

**Comment by Kira-NT** [comment]
Done! If you don't want to wait for the release to be published, you can always grab the latest dev build: https://github.com/Kir-Antipov/sync-fabric/actions/runs/1224208782
