### ISSUE TITLE
Game crashed when right-clicking on the Shell Constructor

### ISSUE THREAD

**Issue by CammiePone** [Kira-NT/sync-fabric#8]
I think it might have to do with me picking Mortal rather than Demon for Requiem's Origins compat stuff, but not totally sure on this.

Requiem Version: 2.0.0-alpha.11
MC Version: 1.17.1
Sync Version: 1.2

https://pastebin.com/3g9fCact

EDIT: Never mind, it was not what I initially thought. I'll update this if I find something before you respond.

**Comment by Kira-NT** [comment]
Deeply appreciate the log! Yep, it has something to do with Requiem. I'll check this

**Comment by CammiePone** [comment]
no problem, hope it gets fixed 'cause this is a cool mod :3

**Comment by Kira-NT** [comment]
Don't worry :)
I already know what the problem is *(somebody uses fields that may not be initialized. And it's not me. Neither is Ladysnake. Minecraft itself is not friendly enough to custom user inventories)*

**Comment by Kira-NT** [comment]
Fixed. You can grab the latest dev build here: https://github.com/Kir-Antipov/sync-fabric/actions/runs/1220867978 :)

**Comment by CammiePone** [comment]
Bog, thank. Time to find more bugs :D
