### ISSUE TITLE
Potential issues regarding the license change from Sync

### ISSUE THREAD

**Issue by CammiePone** [Kira-NT/sync-fabric#9]
Hey, it me again. I noticed you relicensed the project under MIT, while the original was under LGPL. Slight problem with that (barring you having permission from the original author to relicense the project) is that LGPL doesn't allow you to do that. Just don't want you getting into any hot water if iChun decides to come after you for it.

**Comment by Kira-NT** [comment]
Thank you for warning me! Thankfully, there cannot be any problems with this project. Please, read the "License" section of the Readme file more carefully:

> Sync (Fabric) was originally licensed under GNU LGPLv3 license to conform to the original mod, but since the project is not a port, but a reimplementation with its own unique codebase, **I got permission from iChun to change the license to MIT**.

**Comment by CammiePone** [comment]
Oh, I missed that, my bad

**Comment by Kira-NT** [comment]
No problems :)
